### ISSUE TITLE
Okhttp usage

### ISSUE THREAD

**Issue by ber4444** [diebietse/mtls-android#2]
Hi I cannot see how you hooked this up to okhttp. Also, do you have an example for Retrofit and Apollo GraphQL, 2 of the most popular Okhttp based libraries.

**Comment by jedrivisser** [comment]
You can see the okhttp example in the OkHttpFragment here: https://github.com/diebietse/mtls-android/blob/master/app/src/main/java/com/diebietse/mtlsandroidexample/OkHttpFragment.kt#L33

We do not have a specific example for those other libraries, but this creates an okHttpClient that does mtls, so you should be able to tell any libraries that uses OkHttp to use that client

**Comment by ber4444** [comment]
perfect, thanks
